<a href="https://colab.research.google.com/github/SvetlanaSel/data-analysis-tools/blob/main/practice1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Worshop 2.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

#Seliverstova, ADEU-221

1) Импортировать numpy и написать версию

In [ ]:
import numpy as np
print(np.__version__)
np.show_config()

1.23.5
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

2) Создать нулевой вектор размера 10

In [ ]:
v1 = np.zeros(10)
print(v1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3) Создать вектор заполненный 7-ами размера 7

In [ ]:
v2 = np.full(7, 7)
print(v2)

[7 7 7 7 7 7 7]


4) Создать вектор заполненный четными числами от 10 до 100

In [ ]:
v3 = np.arange(10, 101, 2)
print(v3)

[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


5) Создать массив случайных чисел и развернуть его задом наперёд

In [ ]:
v4 = np.random.randint(0, 100, 5)
print('массив а:',v4)
v4_alt = np.flip(v4)
print('перевернутый массив а:',v4_alt)

массив а: [74 14 83 89 38]
перевернутый массив а: [38 89 83 14 74]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [ ]:
v5 = np.arange(9).reshape(3,3)
print(v5)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
v55 = np.arange(1,10).reshape(3,3)
print(v55)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [82]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [ ]:
v7 = np.diag(range(1,4))
v7[v7 == 0] = 7
print(v7)

[[1 7 7]
 [7 2 7]
 [7 7 3]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [ ]:
v8= np.zeros((5,5))
v8 += np.arange(5)
print(v8)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [ ]:
v9 = np.random.randint(10,size = (10, 10))
print(v9)
v9 - v9.mean(axis=1)

[[6 7 7 1 2 0 0 4 8 7]
 [2 9 0 4 8 6 0 8 6 5]
 [7 7 6 0 7 3 6 0 3 6]
 [0 7 9 0 6 8 4 4 9 4]
 [2 0 9 6 1 5 5 9 0 0]
 [3 2 0 1 4 7 8 4 4 6]
 [6 1 0 3 8 3 2 2 7 8]
 [7 4 0 7 7 1 7 4 3 2]
 [5 8 6 2 8 0 5 2 3 1]
 [8 3 9 1 8 3 0 4 5 1]]


array([[ 1.8,  2.2,  2.5, -4.1, -1.7, -3.9, -4. , -0.2,  4. ,  2.8],
       [-2.2,  4.2, -4.5, -1.1,  4.3,  2.1, -4. ,  3.8,  2. ,  0.8],
       [ 2.8,  2.2,  1.5, -5.1,  3.3, -0.9,  2. , -4.2, -1. ,  1.8],
       [-4.2,  2.2,  4.5, -5.1,  2.3,  4.1,  0. , -0.2,  5. , -0.2],
       [-2.2, -4.8,  4.5,  0.9, -2.7,  1.1,  1. ,  4.8, -4. , -4.2],
       [-1.2, -2.8, -4.5, -4.1,  0.3,  3.1,  4. , -0.2,  0. ,  1.8],
       [ 1.8, -3.8, -4.5, -2.1,  4.3, -0.9, -2. , -2.2,  3. ,  3.8],
       [ 2.8, -0.8, -4.5,  1.9,  3.3, -2.9,  3. , -0.2, -1. , -2.2],
       [ 0.8,  3.2,  1.5, -3.1,  4.3, -3.9,  1. , -2.2, -1. , -3.2],
       [ 3.8, -1.8,  4.5, -4.1,  4.3, -0.9, -4. , -0.2,  1. , -3.2]])

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [85]:
v10 = np.random.randint(0, 10, (10, 10))
print(v10)
medians = np.median(v10,axis=1)
result = v10 - medians
print(result)

[[9 1 2 2 4 9 5 5 6 2]
 [5 1 1 1 1 0 1 2 6 5]
 [0 7 4 7 7 6 3 3 0 2]
 [0 2 0 9 5 3 2 3 8 8]
 [0 3 2 1 7 2 1 9 5 0]
 [5 6 3 6 4 9 4 2 5 3]
 [3 7 9 0 6 6 6 2 7 5]
 [9 2 9 1 9 7 1 8 0 0]
 [2 2 8 5 3 3 4 0 0 4]
 [4 2 0 4 1 1 1 0 9 8]]
[[ 4.5  0.  -1.5 -1.   2.   4.5 -1.   0.5  3.   0.5]
 [ 0.5  0.  -2.5 -2.  -1.  -4.5 -5.  -2.5  3.   3.5]
 [-4.5  6.   0.5  4.   5.   1.5 -3.  -1.5 -3.   0.5]
 [-4.5  1.  -3.5  6.   3.  -1.5 -4.  -1.5  5.   6.5]
 [-4.5  2.  -1.5 -2.   5.  -2.5 -5.   4.5  2.  -1.5]
 [ 0.5  5.  -0.5  3.   2.   4.5 -2.  -2.5  2.   1.5]
 [-1.5  6.   5.5 -3.   4.   1.5  0.  -2.5  4.   3.5]
 [ 4.5  1.   5.5 -2.   7.   2.5 -5.   3.5 -3.  -1.5]
 [-2.5  1.   4.5  2.   1.  -1.5 -2.  -4.5 -3.   2.5]
 [-0.5  1.  -3.5  1.  -1.  -3.5 -5.  -4.5  6.   6.5]]


12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [ ]:
v11 = np.random.randint(10,size = (5,5))
print(v11)
max_v = np.max(v11, axis=1)
min_v = np.min(v11, axis=1)
result = np.column_stack((v11, max_v, min_v))
print(result)

[[0 8 5 9 5]
 [3 4 1 9 5]
 [7 4 5 6 8]
 [3 9 7 8 9]
 [0 8 7 9 9]]
[[0 8 5 9 5 9 0]
 [3 4 1 9 5 9 1]
 [7 4 5 6 8 8 4]
 [3 9 7 8 9 9 3]
 [0 8 7 9 9 9 0]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [ ]:
v13 = np.zeros((8, 8), dtype=int)
v13[1::2, ::2] = 1
v13[::2, 1::2] = 1
print(v13)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
